import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { DashboardContextProvider } from "./store/DashboardContext";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Ecommerce dashboard",
  description: "Generated by developer Ashish",
};

const poppins = Poppins({ weight: ['400', '500', '600' , '700'],subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
       suppressHydrationWarning={true}
        className={`${poppins.className} antialiased bg-background`}
      >
        <DashboardContextProvider>
        <ThemeProvider enableSystem={false} attribute="class" >
        {children}
        </ThemeProvider>
        </DashboardContextProvider>
      </body>
    </html>
  );
}
